/* ASCII-Tabelle, sowohl als char als auch als strings */

/* char */

#define C_NUL '\x000'     /* Null Character                     */
#define C_SOH '\x001'     /* Start Of Header                    */
#define C_STX '\x002'     /* Start of TeXt                      */
#define C_ETX '\x003'     /* End of TeXt                        */
#define C_EOT '\x004'     /* End Of Transmission                */
#define C_ENQ '\x005'     /* ENQuiry                            */
#define C_ACK '\x006'     /* ACKnowledge                        */
#define C_BEL '\x007'     /* BELL                               */
#define C_BS  '\x008'     /* BackSpace                          */
#define C_HT  '\x009'     /* Horizontal Tabulator               */
#define C_LF  '\x00A'     /* Line Feed                          */
#define C_VT  '\x00B'     /* Vertical Tabulator                 */
#define C_FF  '\x00C'     /* Form Feed                          */
#define C_CR  '\x00D'     /* Carriage Return                    */
#define C_SO  '\x00E'     /* Shift Out                          */
#define C_SI  '\x00F'     /* Shift In                           */
#define C_DLE '\x010'     /* Data Link Escape                   */
#define C_DC1 '\x011'     /* Device Code 1                      */
#define C_DC2 '\x012'     /* Device Code 2                      */
#define C_DC3 '\x013'     /* Device Code 3                      */
#define C_DC4 '\x014'     /* Device Code 4                      */
#define C_NAK '\x015'     /* Negative AcKnowledge               */
#define C_SYN '\x016'     /* SYNchronize                        */
#define C_ETB '\x017'     /* End of Transmission Block          */
#define C_CAN '\x018'     /* CANcel                             */
#define C_EM  '\x019'     /*                                    */
#define C_SUB '\x01A'     /*                                    */
#define C_ESC '\x01B'     /* ESCape                             */
#define C_FS  '\x01C'     /*                                    */
#define C_GS  '\x01D'     /*                                    */
#define C_RS  '\x01E'     /*                                    */
#define C_US  '\x01F'     /*                                    */

/* strings */

#define S_NUL "\x000"
#define S_SOH "\x001"    
#define S_STX "\x002"    
#define S_ETX "\x003"    
#define S_EOT "\x004"    
#define S_ENQ "\x005"    
#define S_ACK "\x006"    
#define S_BEL "\x007"    
#define S_BS  "\x008"    
#define S_HT  "\x009"    
#define S_LF  "\x00A"    
#define S_VT  "\x00B"    
#define S_FF  "\x00C"    
#define S_CR  "\x00D"    
#define S_SO  "\x00E"    
#define S_SI  "\x00F"    
#define S_DLE "\x010"    
#define S_DC1 "\x011"    
#define S_DC2 "\x012"    
#define S_DC3 "\x013"    
#define S_DC4 "\x014"    
#define S_NAK "\x015"    
#define S_SYN "\x016"    
#define S_ETB "\x017"    
#define S_CAN "\x018"    
#define S_EM  "\x019"    
#define S_SUB "\x01A"    
#define S_ESC "\x01B"    
#define S_FS  "\x01C"    
#define S_GS  "\x01D"    
#define S_RS  "\x01E"    
#define S_US  "\x01F"    
