/* DIALOGIDS.H */

/* Dialoge */
#define IDD_HELPABOUT               5000
#define IDD_MSGLIST                 5020
#define IDD_AREALIST                5040
#define IDD_SETUPOPTIONS            5060
#define IDD_FINDTEXT                5080
#define IDD_REPLYLIST               5120
#define IDD_REPLY                   5140
#define IDD_ATTRIB                  5180
#define IDD_USERNAMES               5220
#define IDD_NODELIST                5240
#define IDD_REQUESTER               5260
#define IDD_ADDRESSES               5290
#define IDD_NICKNAMES               5300
#define IDD_MACROS1                 5320
#define IDD_MSGOPT                  5360
#define IDD_SQUISHOPTIONS           5400
#define IDD_REGISTER                5420
#define IDD_FINDRESULTS             5440
#define IDD_FINDPROGRESS            5460
#define IDD_KLUDGEINFO              5480
#define IDD_NEWUSER                 5500
#define IDD_DELNICKNAME             5520
#define IDD_ALREADYHAVEAREA         5540
#define IDD_NOHELP                  5560
#define IDD_FILEDLG                 5580
#define IDD_AREASETTINGS            5620
#define IDD_AS_GENERAL              5640
#define IDD_AS_MSGBASE              5660
#define IDD_AS_ATTRIB               5680
#define IDD_DELETEAREA              5700
#define IDD_NEWADDRESS              5720
#define IDD_DELUNAME                5740
#define IDD_DELADDRESS              5760
#define IDD_DUPAREAS                5780
#define IDD_ERRORINIFILE            5800
#define IDD_NOINIFILE               5810
#define IDD_OLDINIFILE              5820
#define IDD_DELETE                  5830
#define IDD_CURRENTNAMEADDR         5840
#define IDD_BEENSENT                5850
#define IDD_DISCARD                 5860
#define IDD_EXITNOSAVE              5870
#define IDD_TOOLONG                 5880
#define IDD_ERRORMSGSAVE            5890
#define IDD_INFOMISSING             5900
#define IDD_THREADLIST              5920
#define IDD_INVALIDFILE             5930
#define IDD_ERRORLOAD               5950
#define IDD_EMPTYFILE               5960
#define IDD_EXPORTFILE              5970
#define IDD_CCLISTSETUP             5990
#define IDD_CCLIST                  6010
#define IDD_CCLISTENTRY             6030
#define IDD_CCLISTNAME              6050
#define IDD_DELCCLIST               6070
#define IDD_HAVECCLIST              6080
#define IDD_DELCCENTRY              6090
#define IDD_TEMPLATE                6100
#define IDD_TE_QUOTE                6110
#define IDD_TE_HEADER               6130
#define IDD_TE_FOOTER               6150
#define IDD_TE_REPLY                6170
#define IDD_TE_DAREA                6190
#define IDD_TE_FORWARD              6210
#define IDD_TE_XPOST                6230
#define IDD_TE_CCOPY                6250
#define IDD_THREADSETUP             6260
#define IDD_CCLISTSELECT            6280
#define IDD_NEXTAREA                6300
#define IDD_ERRORSAVE               6310
#define IDD_INVALIDFILENAME         6320
#define IDD_RESEND                  6330
#define IDD_NICKENTRY               6340
#define IDD_HAVENICKNAME            6360
#define IDD_NICKPROMPT              6370
#define IDD_LOOKUPHANDLE            6380
#define IDD_ATTACHSTAT              6390
#define IDD_SQUISHBASEPARAM         6410
#define IDD_AREAOPENERROR           6430
#define IDD_LOOKUP                  6460
#define IDD_IDXOPENERR              6480
#define IDD_DATOPENERR              6490
#define IDD_IDXREADERR              6500
#define IDD_DATREADERR              6510
#define IDD_LOOKUPMEM               6520
#define IDD_ERRREADSQPARAM          6530
#define IDD_ERRWRITESQPARAM         6540
#define IDD_SQPARAMVALUES           6550
#define IDD_TOSSERPATHS             6560
#define IDD_TE_FORWARDFOOTER        6580
#define IDD_DOMAINENTRY             6600
#define IDD_DELDOMAIN               6640
#define IDD_HAVEDOMAIN              6645
#define IDD_FALSEREGISTER           6650
#define IDD_RENUMBER                6660
#define IDD_NLBROWSER               6680
#define IDD_NLLOOKUPS               6700
#define IDD_MODEMTYPES              6720
#define IDD_DEFAULTORIGIN           6880
#define IDD_MACROS2                 6900
#define IDD_MACROS3                 6920
#define IDD_DOMAINS                 6940
#define IDD_STARTUP                 6960
#define IDD_EDITOROPT               6980
#define IDD_TE_FORWARDORDER         7000
#define IDD_NONEXTAREA              7020
#define IDD_WORKERROR               7040
#define IDD_GOTOMESSAGE             7050
#define IDD_AREALISTSETTINGS        7070
#define IDD_AL_SETTINGS_VIEW        7090
#define IDD_AL_SETTINGS_COLORS      7130
#define IDD_LOCKERROR               7150
#define IDD_BCDELERROR              7160
#define IDD_DRIVEREMAP              7170
#define IDD_IMPORTCCLIST            7190
#define IDD_MLISTSETTINGS           7210
#define IDD_ML_SETTINGS_COLORS      7220
#define IDD_ML_SETTINGS_MISC        7240
#define IDD_TPLFOLDER               7260
#define IDD_DELTEMPLATE             7270
#define IDD_CCFOLDER                7280
#define IDD_NOCCLIST                7290
#define IDD_RXFOLDER                7300
#define IDD_RXSETTINGS              7310
#define IDD_RXMONITOR               7320
#define IDD_RXSET_GENERAL           7340
#define IDD_RXSET_MONITOR           7360
#define IDD_DELSCRIPT               7380
#define IDD_NOCCENTRIES             7390
#define IDD_MODQUICKCC              7400
#define IDD_THRLISTSETTINGS         7410
#define IDD_THRLISTCOLORS           7420
#define IDD_DOINGWORK               7440
#define IDD_REPLACENICK             7450
#define IDD_REXXERROR               7480
#define IDD_SAFETY                  7500
#define IDD_CATCHUP                 7520
#define IDD_RXFOLDERSETTINGS        7540
#define IDD_RXHOOKS                 7550
#define IDD_PERSMAILOPT             7570
#define IDD_FINDNOPARTS             7590
#define IDD_FINDNOAREAS             7600
#define IDD_FINDNOTEXT              7610
#define IDD_BOOKMARKS               7620
#define IDD_NOTTHERE                7640
#define IDD_ETOSSERROR              7650
#define IDD_NOAREATAG               7660
#define IDD_NOPATHFILE              7670
#define IDD_TE_ORIGIN               7680
#define IDD_NICKENTRY_FLAGS         7700
#define IDD_NICKENTRY_COMMENTS      7720
#define IDD_ECHOMANAGER             7740
#define IDD_ECHOMGRSETTINGS         7760
#define IDD_EMS_UPLINKS             7780
#define IDD_EMS_EXTDLL              7800
#define IDD_NOUPLINKAREAS           7820
#define IDD_NOACTIONS               7830
#define IDD_DOEXTRACT               7840
#define IDD_EM_DLLLOAD              7850
#define IDD_EM_DLLVER               7860
#define IDD_EM_DLLFUNC              7870
#define IDD_EM_DLLINT               7880
#define IDD_EM_CFGNOTF              7890
#define IDD_EM_INIT                 7900
#define IDD_EM_CFGREAD              7910
#define IDD_EM_CFGWRITE             7920
#define IDD_EM_CFGFORMAT            7930
#define IDD_EM_CFGLINKED            7940
#define IDD_EM_CFGUNLINKED          7950
#define IDD_UPLINK                  7960
#define IDD_DELUPLINK               7980
#define IDD_EM_NOPASS               7990
#define IDD_INITERROR               8000
#define IDD_EM_APPENDAREAS          8010
#define IDD_SEARCH                  8020
#define IDD_PRINTSETUP              8040
#define IDD_PS_LIST                 8060
#define IDD_PS_BORDERS              8080
#define IDD_PS_FONTS                8100
#define IDD_PS_OUTPUT               8120
#define IDD_TOOLBARCONFIG           8140
#define IDD_REGONLY                 8160
#define IDD_REQ_ADDLIST             8170
#define IDD_REQ_DELLIST             8190
#define IDD_REQ_ADDFILE             8200
#define IDD_REQ_SETPASS             8220
#define IDD_REQ_ERROR               8240
#define IDD_CFGDLLERROR             8250
#define IDD_SU_OPENWIN              8260
